name: Hit KHV scrape endpoint

on:
  push:
    branches: [master]
  schedule:
    - cron: "* */6 * * *"

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Scrape KHV
        id: scrapeRequest
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://khv-api-dev.onrender.com/scrape"
          method: "GET"
          timeout: 300000
      - name: Show Response
        run: |
          echo ${{ steps.scrapeRequest.outputs.response }}
          echo ${{ steps.scrapeRequest.outputs.headers }}
          echo ${{ fromJson(steps.scrapeRequest.outputs.response)}}
