name: Hit KHV scrape endpoint

on:
  schedule:
    - cron: "* */2 * * *"

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate
        id: authRequest
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{secrets.AUTH_URL}}
          data: '{"client_id": ${{secrets.CLIENT_ID}}, "client_secret": ${{secrets.CLIENT_SECRET}},"audience": ${{secrets.AUTH_AUDIENCE}},"grant_type": "client_credentials"}'
          method: "POST"
          timeout: 300000
      - name: Scrape KHV
        id: scrapeRequest
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://khv-api-dev.onrender.com/scrape"
          bearerToken: ${{ fromJson(steps.authRequest.outputs.response).access_token}}
          method: "GET"
          timeout: 300000
      - name: Show Response
        run: |
          echo ${{ steps.scrapeRequest.outputs.response }}
          echo ${{ steps.scrapeRequest.outputs.headers }}
          echo ${{ fromJson(steps.scrapeRequest.outputs.response)}}
